### ISSUE TITLE
Dev Environment Meeting

### ISSUE THREAD

**Issue by iggy14750** [TrainingMontage/prod#1]
A session sometime to discuss the dev/build environment and the tools we are going to use. 
I noticed that @AlecRosenbaum and I have made basically all the decisions about this, so we should probably share our plans with everyone.

1. GitHub: how we are going to use git and GitHub, our policy on branching, how to add permission to TravisCI, Issues, etc
2. TravisCI: What it is, how we're going to use it, etc
3. Gradle: What it is, how we're going to use it.
4. Javadoc, sensing a theme.

And anything else we might want to add.
Please comment to add input. I think doing this at some dedicated time will be good to get everyone up to speed and talk about our expectations.
Notice that this is not high priority; requirements and UI are higher priority right now.

**Comment by AlecRosenbaum** [comment]
Lets discuss this in the next Lab (September 14th)
